name: runner-cache-cross-os

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: runner-cache upload (${{ matrix.os }})
    steps:
    - uses: actions/checkout@v3
    - name: Create file to cache
      shell: bash
      run: |
        mkdir test-cache
        echo "foo" > test-cache/test.txt
    - uses: actions/cache@v3.1.0-beta
      with:
        path: test-cache
        key: ${{ matrix.os }}-runner-${{ github.run_number }}-${{ github.run_attempt }}

  restore:
    needs: upload
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        key: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: runner-cache restore (${{ matrix.os }}) with key (${{ matrix.key }})
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3.1.0-beta
      id: cache
      with:
        path: test-cache
        key: ${{ matrix.key }}-runner-${{ github.run_number }}-${{ github.run_attempt }}

    - name: Fail if cache not found
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        echo "Cache not found, upload failed"
        exit 1
    - name: Output cache content
      run: |
        cat test-cache/test.txt
    - name: Check cache contents
      shell: bash
      run: if [ $(cat test-cache/test.txt) == "foo" ]; then echo "Cache contents verified."; exit 0; else echo "Cache invalid"; exit 1; fi
